### PR TITLE
stars-4: add new data

### PR DESCRIPTION
**Pull request by stqa2014**
added new data

### CODE REVIEW

**Review by Lenajava1 — APPROVED** [review]
Keep it up!

**Review by kmariia777 — APPROVED** [review]

**Review by kmariia777 — APPROVED** [review]

**Comment by TatyanaTX** [comment]
Approved

**Review by stqa2014 — COMMENTED** [review]
Looks good

**Comment by stqa2014** [comment]
Looks good

**Review by okarpovich — APPROVED** [review]
Great job!

**Review by anyakid — APPROVED** [review]
Nice job!

**Pull request closed without merging**
